### PR TITLE
Update index.html footer to 2015 from 2014

### PR DESCRIPTION
**Pull request by nsamsami**

### CODE REVIEW

**Comment by dustinlarimer** [comment]
thanks @nsamsami :)

**Comment by nsamsami** [comment]
Hey Dustin! It still looks like 2014 is showing up on http://keen.github.io/dashboards/

**Comment by dustinlarimer** [comment]
@nsamsami that update only changed the footer on layouts/index.html.. these templates don't use any sort of inheritance so you'll just need to do it manually for all :)

**Comment by nsamsami** [comment]
Oh got it! Will do it and resubmit :)

**Pull request merged**
