### PR TITLE
Adds a package.json and .npmignore for npm deployment

### PR DESCRIPTION
**Pull request by preynal**
Awesome work on this project, thanks a lot!

It would be really helpful if you could merge this **and deploy the package to npm** (the keen-dashboards name is available).

A lot of people are now using webpack or other module bundlers, and rely on npm for their dependencies. Not having a package.json forces us to use bower, or write custom scripts to pull the source from github.

Looking forward to your feedback.

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Yes, please!! This would be really helpful to me too.

**Comment by g-wilson** [comment]
+1

**Comment by preynal** [comment]
@dustinlarimer do you mind merging ? it's been open for 5 months, 
thanks

**Comment by timfalls** [comment]
@preynal @paulmelnikow @g-wilson just wanted to let you know that I noticed your comments and am getting in touch with the team to get an update here. Thanks for your patience 🙂

**Comment by paulmelnikow** [comment]
Thanks @timfalls, would appreciate it!

**Comment by dustinlarimer** [comment]
This has been deployed from our master branch, and is available under `keen-dashboards@0.1.1` package: https://www.npmjs.com/package/keen-dashboards

Thanks for the persistent nudging, everyone! We have some exciting new things on the way in dashboard-land. Stay tuned! :rocket:

**Pull request closed without merging**
